In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))
oneArray = np.array(list1)
print(oneArray)
print(type(oneArray))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


## ndadday 与 Python 原生list运算效率对比

In [3]:
import random
import time

import numpy as np

a = []
for i in range(100000000):
    a.append(random.random())
print('随机完毕')
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
print('转换完毕')
t4 = time.time()
sum2 = np.sum(b)
t5 = time.time()
print('原生list求和耗时：', t2 - t1)
print('numpy数组求和耗时：', t5 - t4)

随机完毕
转换完毕
原生list求和耗时： 0.6605546474456787
numpy数组求和耗时： 0.16494059562683105


In [4]:
t1 = np.array([1, 2, 3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
print(type(range(10)))
t2 = np.array(range(10))
print(t2)
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
t3 = np.arange(0, 10, 2)
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(twoArray)
print(list2)
twoArray.tolist()

[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


[[1, 2], [3, 4], [5, 6]]

## 常用属性

In [10]:
list2 = [[1, 2], [3, 4], [5, 6]]
twoArray = np.array(list2)
print(twoArray.shape)  #形状(行数，列数)
print(twoArray.dtype)  #数据类型，默认int32，4个字节，数据范围 -21亿 到 21亿
print(twoArray.size)  #元素个数
print(twoArray.ndim)  #维度

(3, 2)
int32
6
2


## 调整数组形状

In [13]:
four = np.array([[1, 2, 3], [4, 5, 6]])

print(four)

four1 = four
print(id(four))
four.shape = (3, 2)
print(four)
print(id(four))
print(id(four1))
four1.shape = (2, 3)
print(four1)
print(id(four1))
print(id(four))

[[1 2 3]
 [4 5 6]]
2962878323312
[[1 2]
 [3 4]
 [5 6]]
2962878323312
2962878323312
[[1 2 3]
 [4 5 6]]
2962878323312
2962878323312


In [15]:
# 将多维数组展平成一维数组
five = four.reshape((6,), order='C')
#'C'为行优先，'F'为列优先
six = four.flatten()
print(five)
print(six)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [19]:
seven = five.reshape(3, 2)
print(seven)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
print('-' * 50)
t = np.arange(24)
print(t)
print(t.shape)
print(t.ndim)

t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)
print(t1.ndim)

--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
2


In [25]:
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [27]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


In [28]:
#数组转换为列表
a = np.array([9, 12, 88, 14, 25])
print(type(a))
b = a.tolist()
print(type(b))
print(b)

<class 'numpy.ndarray'>
<class 'list'>
[9, 12, 88, 14, 25]


## Numpy的数据类型

In [34]:
import random

f = np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(f.itemsize)  # 1 字节 np.int16
print(f.dtype)

2
int16


In [35]:
#拓展随机生成小数
#使用python语法、保留两位
print(round(random.random(), 2))
#np.float16 半精度浮点数
#np.float32 单精度浮点数
#np.float64 双精度浮点数
arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.dtype)
print(arr.itemsize)
#取小数点后两位
print(np.round(arr, 2))

0.77
[0.45135964 0.46988081 0.33234382 0.06556707 0.65838085 0.4198312
 0.8295855  0.31297579 0.59254861 0.28484848]
float64
8
[0.45 0.47 0.33 0.07 0.66 0.42 0.83 0.31 0.59 0.28]


In [37]:
#列表不可以和整数进行相加
[1, 2, 3] + 5  #TypeError: can only concatenate list (not "int") to list

TypeError: can only concatenate list (not "int") to list

In [40]:
#由于numpy的广播机制，可以对不同形状的数组进行运算，加减乘除的值被广播到所有元素上进行运算
t1 = np.arange(24).reshape((6, 4))
print(t1)
print('-' * 20)
t2 = t1.tolist()
print(t1 + 2)
# print(t2 + 2)  #不能对列表进行加整数操作
print('-' * 20)
print(t1 * 2)
print('-' * 20)
print(t1 / 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [41]:
#形状相同，才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [42]:
#shape不同，不能进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((4, 6))
print(t1)
print(t2)
print(t1 + t2)  #ValueError: operands could not be broadcast together with shapes (6,4) (4,6)
print(t1 - t2)  #ValueError: operands could not be broadcast together with shapes (6,4) (4,6)
print(t1 * t2)  #ValueError: operands could not be broadcast together with shapes (6,4) (4,6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]


ValueError: operands could not be broadcast together with shapes (6,4) (4,6) 

In [48]:
#特殊情况：一维数组和二维数组的运算，一维的元素个数和二维的列数相同，才可以进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
print(t1 - t
2)

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


### 结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1

In [50]:
#练习轴
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('-' * 20)
print(np.sum(a, axis=0))  # 按哪个轴求和，哪个轴就没了
print('-' * 20)
print(np.sum(a, axis=1))
print('-' * 20)
print(np.sum(a))

[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21


In [52]:
#索引和切片
import numpy as np

a = np.arange(10)

#如果只放置一个参数，如[2]，将返回与该参数对应的元素
print(a[0], a)

#如哦为[2:]，表示从索引2开始的所有元素
print(a[2:])

print(a[2:8:2])  #切片是左闭右开的，即[2,8)

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [55]:
#二维切片
import numpy as np

t1 = np.arange(24).reshape((4, 6))
print(t1)
print('-' * 20)
print(t1[1])  #取一行（一行代表是一行数据，索引也是从0开始的） print(t1[1, :])
print('-' * 20)
print(t1[1:])  #取连续的多行
print('-' * 20)
print(t1[1:3, :])  #取多行多列
print('-' * 20)
print(t1[[0, 2, 3]])  #取多行多列


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[ 6  7  8  9 10 11]
--------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
